version: '3'
services:
  # Next.js Application Service
  nextjs:
    build:
      context: ./ 
      dockerfile: Dockerfile  # Point to your Next.js Dockerfile

  # Nginx Service
  nginx:
    image: nginx:latest  # Use the official Nginx image
    ports:
      - "80:80"  # Customize the port if needed
    volumes:
      #- ./nginx-config/nginx.conf:/etc/nginx/nginx.conf  # Customize Nginx configuration path
      #- ./nextjs-app/build:/usr/share/nginx/html  # Customize the path to your Next.js build directory
      - ./out:/usr/share/nginx/html  # Customize the path to your Next.js build directory

